### PR TITLE
fix: fzf-lua invisible selection

### LINKED ISSUE #283: bug: fzf-lua text invisible
### Neovim version (nvim -v)

NVIM v0.11.0-dev-358+g6a886a251

### Terminal / multiplexer

konsole

### Describe the bug

hello
when using fzf lua most of the item listing are invisible

I'm not sure if it's something we can fix in rose pine, but I don't know where to find help otherwise, maybe this can be added as a plugin like some other in the wiki

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
	rose_pine = "https://github.com/rose-pine/neovim",
	fzf_lua = "https://github.com/ibhagwan/fzf-lua",
}

for name, url in pairs(plugins) do
	local install_path = "/tmp/nvim/site/pack/test/start/" .. name
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
end

require("rose-pine").setup({})

vim.cmd("colorscheme rose-pine")

require("fzf-lua").setup({ fzf_colors = true })

-- then do FzfLua files
```

### PR DESCRIPTION
**Pull request by sjclayton**
Found the offending highlight groups and corrected them. 😄 

Closes #283 

Result:

### CODE REVIEW

File: lua/rose-pine.lua [hunk 1]
```diff
@@ -667,13 +667,14 @@ local function set_highlights()
...
-		FzfLuaHeaderText = { fg = palette.love },
-		FzfLuaHeaderBind = { fg = palette.rose },
-		FzfLuaBufFlagCur = { fg = palette.subtle },
 		FzfLuaBufFlagAlt = { fg = palette.subtle },
+		FzfLuaBufFlagCur = { fg = palette.subtle },
+		FzfLuaCursorLine = { fg = palette.text, bg = palette.overlay },
+		FzfLuaHeaderBind = { fg = palette.rose },
+		FzfLuaHeaderText = { fg = palette.love },
+		FzfLuaNormal = { fg = palette.text, bg = palette.surface },
+		FzfLuaTitle = { fg = palette.foam, bg = palette.surface, bold = styles.bold },
```
Comment (mvllow) [inline lua/rose-pine.lua:677]: Let's link these two groups so they respect both `groups.panel` and `styles.transparency`. This also fixes the title having a different background than the borders :)

```suggestion
		FzfLuaNormal = { link = "NormalFloat" },
		FzfLuaTitle = { link = "FloatTitle" },
```

Comment (sjclayton) [reply lua/rose-pine.lua]: Resolved in latest commit.

**Comment by mirsella** [comment]
hey ! thanks for the awesome work ! in case the maintainer doesnt look at the update on the issue, for now this pr doesn't fix the issue, lets wait before merging it

**Comment by sjclayton** [comment]
@mirsella 

I installed fzf-lua, and this is what I have on `NVIM v0.11.0-dev-486+g9793a9777`



If you are on the latest nightly or even try nvim stable 0.10.0... they both look exactly the same. If yours doesn't look like that then there is something else getting overridden somewhere in your config.

**Comment by mirsella** [comment]
update this PR is working as expected, it was a problem on my setup !

**Comment by sjclayton** [comment]
All good to merge it appears.

**Comment by mvllow** [comment]
Thanks everyone :)
